import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../lib/Providers";
import { Toaster } from "react-hot-toast";
import MainLayout from "@/components/layout/RootLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className="text-black min-h-screen ">
          <Toaster position="bottom-left" />

          {children}
        </body>
      </html>
    </Providers>
  );
}
